CREATE DATABASE BYCE;
CONNECT BYCE;

CREATE TABLE DEVICES(
    UID VARCHAR(128) PRIMARY KEY,
    NAME_DEVICE VARCHAR(128),
    MODEL VARCHAR(128),
    OS_VERSION VARCHAR(128)
);

CREATE TABLE DATALOG(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    UID VARCHAR(128) NOT NULL,
    LOG_DATE DATE NOT NULL,
    LOG_TIME TIME NOT NULL,
    BAT_LEVEL INTEGER NOT NULL,
    INCHARGE BOOLEAN NOT NULL,
    FOREIGN KEY(UID) REFERENCES DEVICES(UID)
);
