{
 "title": "byce-grafana",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Panoramica", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Battery level",
   "type": "bargauge",
   "description": "Livello delle batterie di tutti i dispositivi",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT battery as \"AlbyAndroid\" FROM Dataset d1 WHERE d1.name=\"AlbyAndroid\" ORDER BY d1.data DESC, d1.tempo DESC LIMIT 1; "
    },
    {
     "rawSql": "SELECT battery as \"S88plus\" FROM Dataset d1 WHERE d1.name=\"S88plus\" ORDER BY d1.data DESC, d1.tempo DESC LIMIT 1; "
    }
   ]
  },
  {
   "title": "Charging",
   "type": "gauge",
   "description": "See if the device are plugged or not",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT incharge as \"AlbyAndroid\" FROM Dataset d1 WHERE d1.name=\"AlbyAndroid\" ORDER BY d1.data DESC, d1.tempo DESC LIMIT 1; "
    },
    {
     "rawSql": "SELECT incharge as \"S88plus\" FROM Dataset d1 WHERE d1.name=\"S88plus\" ORDER BY d1.data DESC, d1.tempo DESC LIMIT 1; \n"
    }
   ]
  },
  { "title": "Dettagliato", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "AlbyAndroid giornaliero",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT battery, tempo FROM Dataset d1 WHERE d1.data=CURRENT_DATE AND d1.name=\"AlbyAndroid\";\n"
    }
   ]
  },
  {
   "title": "S88 giornaliero",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT battery, tempo FROM Dataset d1 WHERE d1.data=CURRENT_DATE AND d1.name=\"S88plus\";\n"
    }
   ]
  },
  {
   "title": "AlbyAndroid",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT battery, tempo FROM Dataset d1 WHERE d1.name=\"AlbyAndroid\" ORDER BY d1.data DESC, d1.tempo DESC LIMIT 1;\n"
    }
   ]
  },
  {
   "title": "S88Plus",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT battery, tempo FROM Dataset d1 WHERE d1.name=\"S88plus\" ORDER BY d1.data DESC, d1.tempo DESC LIMIT 1;"
    }
   ]
  }
 ]
}