{
 "title": "BYCE-Dashboard",
 "time": { "from": "2022-06-02T17:12:57.000Z", "to": "2022-06-02T17:32:38.000Z" },
 "panels": [
  {
   "title": "Battery level",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT BAT_LEVEL, NAME_DEVICE FROM DATALOG DL1\nINNER JOIN DEVICES D ON D.UID = DL1.UID\nWHERE DL1.LOG_DATE=CURRENT_DATE AND NOT EXISTS (SELECT * FROM DATALOG DL2 WHERE\n    DL1.UID=DL2.UID AND\n     DL1.LOG_DATE=DL2.LOG_DATE AND DL1.LOG_TIME<DL2.LOG_TIME)\nGROUP BY BAT_LEVEL, NAME_DEVICE;\n"
    }
   ]
  },
  {
   "title": "In charge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nSELECT DL1.IN_CHARGE, DL1.LOG_TIME, D.NAME_DEVICE FROM DATALOG DL1\nINNER JOIN DEVICES D ON DL1.UID=D.UID\nWHERE DL1.LOG_DATE=CURRENT_DATE AND\nNOT EXISTS(SELECT * FROM DATALOG DL2 WHERE\nDL1.LOG_TIME<DL2.LOG_TIME AND\nDL1.UID=DL2.UID AND\nDL1.LOG_DATE=DL2.LOG_DATE);\n"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(LOG_TIME) AS time_sec, BAT_LEVEL AS value, NAME_DEVICE\nFROM DATALOG DL1\nINNER JOIN DEVICES D1 ON D1.UID=DL1.UID\nWHERE DL1.LOG_DATE=CURRENT_DATE\nGROUP BY time_sec, value, NAME_DEVICE\nORDER BY time_sec, value, NAME_DEVICE;\n"
    }
   ]
  },
  {
   "title": "Dettaglio Alby Android",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "\nSELECT UNIX_TIMESTAMP(LOG_TIME) AS time_sec, BAT_LEVEL AS value\nFROM DATALOG DL1\nINNER JOIN DEVICES D ON D.UID = DL1.UID\nWHERE NAME_DEVICE='AlbyAndroid'\nGROUP BY time_sec, value\nORDER BY time_sec, value"
    }
   ]
  },
  {
   "title": "All devices",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "rawSql": "SELECT * FROM DEVICES;" }
   ]
  }
 ]
}